sudo: required
jobs:
  include:
   - os: linux
     arch: amd64
   - os: linux
     arch: arm64-graviton2
     virt: lxd
     group: edge
  
language: python
install: true

services:
  - docker

script: true

after_success:
  - echo $TRAVIS_REPO_SLUG
  - export TRAVIS_REPO_SLUG=anjanasuraj/concourse-email-resource
  - echo $TRAVIS_CPU_ARCH
  - if [ "${TRAVIS_CPU_ARCH}" == "arm64" ]; then TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG}_arm64; fi
  - echo $TRAVIS_REPO_SLUG
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t $TRAVIS_REPO_SLUG .;
    docker login -u="anjanasuraj" -p="Orca@12345";
    docker push $TRAVIS_REPO_SLUG;
    fi
