sudo: required
arch:
  - amd64
  - arm64
  
language: python
install: true

services:
  - docker

script: true

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    - if [ "${TRAVIS_CPU_ARCH}" == "arm64" ]; then
      docker build -t anjana/concourse-email-resource_arm64 .;
      docker login -u="anjanasuraj" -p="Orca@12345";
      docker push anjana/concourse-email-resource_arm64;
      else
      docker build -t anjana/concourse-email-resource .;
      docker login -u="anjanasuraj" -p="Orca@12345";
      docker push anjana/concourse-email-resource;
    fi
