sudo: required
arch:
  - amd64
  - arm64
  
language: python
install: true

services:
  - docker

script: true

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    - if [ "${TRAVIS_CPU_ARCH}" == "arm64" ]; then
      set image_name concat($TRAVIS_REPO_SLUG,"_arm64")
      docker build -t $image_name .;
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push $image_name;
      else
      docker build -t $TRAVIS_REPO_SLUG .;
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push $TRAVIS_REPO_SLUG;
    fi
